M48
; DRILL file {KiCad 7.0.10} date Thursday, January 30, 2025 at 11:53:40 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-30T23:53:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X5.0421Y-1.2402
X5.4921Y-1.2402
X5.987Y-1.2402
X6.437Y-1.2402
M30
