M48
; DRILL file {KiCad 7.0.10} date Tue Feb  4 22:51:24 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-04T22:51:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0945
%
G90
G05
T1
X5.2924Y-2.5674
X5.5199Y-2.5674
T2
X4.43Y-3.1677
X4.47Y-3.3677
X4.51Y-3.1677
T3
X6.165Y-3.5953
T4
X7.5698Y-2.5627
X8.1698Y-2.5627
M30
